//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_moving_icon_H
#define METASPRITE_moving_icon_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define moving_icon_TILE_W 8
#define moving_icon_TILE_H 8
#define moving_icon_WIDTH 40
#define moving_icon_HEIGHT 40
#define moving_icon_TILE_COUNT 25

BANKREF_EXTERN(moving_icon)

extern const uint8_t moving_icon_tiles[400];
extern const unsigned char moving_icon_sprite[5][5];

#endif
