//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_O_H
#define METASPRITE_O_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define O_TILE_ORIGIN 0
#define O_TILE_W 8
#define O_TILE_H 8
#define O_WIDTH 32
#define O_HEIGHT 32
#define O_TILE_COUNT 16

BANKREF_EXTERN(O)

extern const uint8_t O_tiles[256];

extern const unsigned char O_map[16];

#endif
