//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_press_start_H
#define METASPRITE_press_start_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define press_start_TILE_ORIGIN 0
#define press_start_TILE_W 8
#define press_start_TILE_H 8
#define press_start_WIDTH 104
#define press_start_HEIGHT 24
#define press_start_TILE_COUNT 39

BANKREF_EXTERN(press_start)

extern const uint8_t press_start_tiles[624];

extern const unsigned char press_start_map[39];

#endif
