//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tic_tac_toe_H
#define METASPRITE_tic_tac_toe_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tic_tac_toe_TILE_ORIGIN 0
#define tic_tac_toe_TILE_W 8
#define tic_tac_toe_TILE_H 8
#define tic_tac_toe_WIDTH 160
#define tic_tac_toe_HEIGHT 144
#define tic_tac_toe_TILE_COUNT 74

BANKREF_EXTERN(tic_tac_toe)

extern const uint8_t tic_tac_toe_tiles[1184];

extern const unsigned char tic_tac_toe_map[360];

#endif
