//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tris_board_H
#define METASPRITE_tris_board_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tris_board_TILE_ORIGIN 0
#define tris_board_TILE_W 8
#define tris_board_TILE_H 8
#define tris_board_WIDTH 160
#define tris_board_HEIGHT 144
#define tris_board_TILE_COUNT 28

BANKREF_EXTERN(tris_board)

extern const uint8_t tris_board_tiles[448];

extern const unsigned char tris_board_map[360];

#endif
