//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_X_H
#define METASPRITE_X_H

#include <stdint.h>
#include <gbdk/platform.h>

#define X_TILE_W 8
#define X_TILE_H 8
#define X_WIDTH 32
#define X_HEIGHT 32
#define X_TILE_COUNT 12

BANKREF_EXTERN(X)

extern const uint8_t X_tiles[192];

extern const unsigned char X_map[16];

#endif
